name: Build & Deploy Branch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout source
      - uses: actions/checkout@v4

      # node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # install + build
      - run: npm ci
      - run: npm run build

      # copy art into build
      - run: cp -r art dist/art

      # push dist to deploy branch
      - name: Deploy to deploy branch
        run: |
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "deploy build"

          git branch -M deploy
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin deploy
